export interface YouTubeTranscriptSegment {
  id?: string;
  start: number; // in seconds
  end: number; // in seconds
  duration?: number;
  text: string;
  speaker?: string;
  chapter?: string;
}

export interface YouTubeVideoMetadata {
  videoId: string;
  url: string;
  title: string;
  authorName: string;
  authorUrl?: string;
  thumbnailUrl: string;
  durationSeconds?: number;
  viewCount?: string;
  publishDate?: string;
  embedUrl: string;
}

export interface YouTubeSubtitleTrack {
  code: string;
  name: string;
  isAutoGenerated: boolean;
  isDefault?: boolean;
}

export interface YouTubeChapter {
  title: string;
  startTime: number;
  endTime?: number;
  summary?: string;
}

export interface YouTubeTranscriptData {
  metadata: YouTubeVideoMetadata;
  languageDetected: string;
  availableTracks: YouTubeSubtitleTrack[];
  selectedTrack?: string;
  segments: YouTubeTranscriptSegment[];
  fullText: string;
  wordCount: number;
  characterCount: number;
  source: "youtube_official_captions" | "youtube_auto_captions" | "ai_speech_reconstruction";
  aiGeneratedDetails?: {
    summary?: string;
    keyTakeaways?: string[];
    chapters?: YouTubeChapter[];
    keyQuotes?: string[];
  };
}

export interface YouTubeAiChat {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
}
